### ISSUE TITLE
When using API 35.0 not able set testLevel to run all tests

### ISSUE THREAD

**Issue by yiliangx** [solenopsis/Solenopsis#226]
sf.runAllTests is set to true, however when issuing "bsolenopsis push" project is deployed but no test classes are ran.

**Comment by pcon** [comment]
Are you pushing to a production instance or to a sandbox instance?

**Comment by yiliangx** [comment]
I'm pushing to a Developer Edition Org

**Comment by pcon** [comment]
This is unfortunately a limitation of the DE orgs.  Since they do not require tests to run at deployment, the runAllTests flag is not honored.  You can instead run

```bsolenopsis run-tests```

and that will run all the tests in the given org.

**Comment by shahmovahedi** [comment]
It would be good to be able to validate + run all tests in a single deployment before actually committing the changes. Your suggestion would actually deploy the code in 1 step, then run test classes in the 2nd step. This means in case of test class failures there is no way of knowing before actually deploying the code. Thanks for your great work @pcon !

**Comment by shahmovahedi** [comment]
Thanks for the quick response, I'm new to solenopsis. I previously used Jenkins+ANT migration - I was hoping for an equivalent of below:

 	 <target name="validateQA">
      	<sf:deploy username="${sf.username.qa}" password="${sf.password.qa}" serverurl="${sf.serverurl.qa}" maxPoll="${sf.maxPoll}" deployRoot="codeToDeploy" pollWaitMillis="${sf.pollWaitMillis}" **testLevel="RunLocalTests" checkOnly="true"**/>
    </target>

**Comment by LopezRegaladoFj** [comment]
I am in the same point right now, I have generated a dumpFile using the property `sf.dumpFiles` and `sf.runAllTest=true` in order to check the details. In the file generated after run `solenopsis push` I can view the property `testLevel="RunLocalTests`, If a check this build.xml directly using the ant command:
`ant -f [patch to build.xml]` all test are running in the sandbox deployment.

But the behaviour is not the same using `solenopsis push`, in this case no test are running during the deployment
