### ISSUE TITLE
jdk/ant version issue?

### ISSUE THREAD

**Issue by huanzhang** [solenopsis/Solenopsis#24]
I am not sure, but I got following when destructive-push.

/usr/share/solenopsis/ant/solenopsis.xml:206: The following error occurred while executing this line:
/usr/share/solenopsis/ant/util/sfdc-util.xml:822: Failed to login: Failed to parse detail:  START_TAG seen ...</faultstring><detail><sf:LoginFault xsi:type="sf:LoginFault">... @1:434 due to: com.sforce.ws.ConnectionException: Incompatible type 'class com.sforce.soap.partner.fault.LoginFault' specified as xsi:type. It must be a subclass of 'class com.sforce.ws.ConnectionException'

Please note:
$ java -version
java version "1.6.0_38"
Java(TM) SE Runtime Environment (build 1.6.0_38-b05)
Java HotSpot(TM) 64-Bit Server VM (build 20.13-b02, mixed mode)

$ ant -version
Apache Ant(TM) version 1.8.3 compiled on February 29 2012

**Comment by suprinder** [comment]
@huanzhang Can you elaborate what credential setup was done for this. Thanks

**Comment by sfloess** [comment]
@suprinder - it's been quite a few years since we all looked at this.  If memory serves, the token itself was bad.

**Comment by huanzhang** [comment]
@sfloess thanks for your reply~ 💯

**Comment by KhogaEslam** [comment]
OK, it's login fault error, but what's the root cause of the parsing issue?

**Comment by pcon** [comment]
@KhogaEslam Can you please share your current java and ant version and the exact error you are seeing?

**Comment by sfloess** [comment]
@KhogaEslam - my apologies for a late response.  I have been on PTO since last week - all I had with me was my phone and it's the least ideal medium to do much :)

There isn't a parsing issue.  This is a class cast problem from within the SFDC ant jar.  The code appears to expect a com.sforce.soap.partner.fault.LoginFault class - it's been a few years since I've looked at this, but if it's important, I can dig in to provide a more thorough explanation.  It may be possible to fix this, but considering that we are using the SFDC jar file (in ant), it may require a bit of investigation on my part.

However, if you feel strongly about it, I will definitely look into it - np at all!  :)

**Comment by KhogaEslam** [comment]
@pcon & @sfloess 
Sorry, the bug is not related to @Solenopsis at all, It's related to SFDS JAR 
I was redirected from SF [forum](https://developer.salesforce.com/forums/?id=906F0000000AXj1IAG) .
Sorry, again.

**Comment by sfloess** [comment]
@KhogaEslam - no worries at all!

Thanks for reaching out to us!
